name: Deploy Origindots WEB Api in Container

on:
  push:
    branches:
      - kemal

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t origindots-web-test .

    - name: Run origindots in container
      run: |
        docker ps -a -q --filter "name=origindots-web-test" | xargs -r docker stop
        docker ps -a -q --filter "name=origindots-web-test" | xargs -r docker rm
        docker run --name origindots-web-test -p 3030:3000   -d origindots-web-test 
